### ISSUE TITLE
Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by bpeacock44** [biocore/empress#567]
Hello! I installed the standalone version of empress a couple of weeks ago and it's been working beautifully. Yesterday I tried running it and got the error seen below. I went back and ran it again on data that had already worked and got the same error. Then I tried installing it on a local linux machine and got the same error. The error also occurs when I type run `empress --help`. 

```sh
[usr] programs$ empress --help
Traceback (most recent call last):
  File "/home/borneman/.local/bin/empress", line 5, in <module>
    from empress.scripts._cli import empress
  File "/home/borneman/.local/lib/python3.10/site-packages/empress/__init__.py", line 9, in <module>
    from empress.core import Empress
  File "/home/borneman/.local/lib/python3.10/site-packages/empress/core.py", line 24, in <module>
    from emperor import Emperor
  File "/home/borneman/.local/lib/python3.10/site-packages/emperor/__init__.py", line 12, in <module>
    from emperor.core import Emperor
  File "/home/borneman/.local/lib/python3.10/site-packages/emperor/core.py", line 19, in <module>
    from skbio import OrdinationResults
  File "/home/borneman/.local/lib/python3.10/site-packages/skbio/__init__.py", line 12, in <module>
    import skbio.io  # noqa
  File "/home/borneman/.local/lib/python3.10/site-packages/skbio/io/__init__.py", line 290, in <module>
    import_module("skbio.io.format.clustal")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/borneman/.local/lib/python3.10/site-packages/skbio/io/format/clustal.py", line 148, in <module>
    from skbio.alignment import TabularMSA
  File "/home/borneman/.local/lib/python3.10/site-packages/skbio/alignment/__init__.py", line 211, in <module>
    from ._tabular_msa import TabularMSA
  File "/home/borneman/.local/lib/python3.10/site-packages/skbio/alignment/_tabular_msa.py", line 18, in <module>
    from skbio.sequence import Sequence
  File "/home/borneman/.local/lib/python3.10/site-packages/skbio/sequence/__init__.py", line 329, in <module>
    from ._substitution import SubstitutionMatrix
  File "/home/borneman/.local/lib/python3.10/site-packages/skbio/sequence/_substitution.py", line 12, in <module>
    from skbio.stats.distance import DissimilarityMatrix
  File "/home/borneman/.local/lib/python3.10/site-packages/skbio/stats/__init__.py", line 69, in <module>
    from ._subsample import subsample_counts, isubsample
  File "/home/borneman/.local/lib/python3.10/site-packages/skbio/stats/_subsample.py", line 18, in <module>
    from biom import subsample as biom_subsample
  File "/home/borneman/.local/lib/python3.10/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/home/borneman/.local/lib/python3.10/site-packages/biom/table.py", line 196, in <module>
    from ._filter import _filter
  File "biom/_filter.pyx", line 1, in init biom._filter
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
````

**Comment by fedarko** [comment]
Thanks for reporting this! I was able to reproduce this issue. To make a long story short, I think the issue is that you installed (either directly or indirectly) a numpy version >= 2, which is currently incompatible with Empress' dependencies. We've already seen these numpy versions cause other problems with Empress (#561), but this particular one is new to me.

## Reproducing the issue

Creating a fresh conda environment with Python 3.10, numpy >= 2, and Cython -- then installing Empress into this environment -- reproduces your issue:

```console
$ mamba create -n etest20241209 python=3.10 "numpy >=2" cython  # installs numpy 2.1.3
$ conda activate etest20241209
$ pip install empress
$ empress --help  # gives me the same error --
Traceback (most recent call last):
  File "/home/marcus/anaconda3/envs/etest20241209/bin/empress", line 5, in <module>
    from empress.scripts._cli import empress
  File "/home/marcus/anaconda3/envs/etest20241209/lib/python3.10/site-packages/empress/scripts/_cli.py", line 10, in <module>
    from empress._plot_utils import save_viz, prepare_pcoa, check_and_process_files
  File "/home/marcus/anaconda3/envs/etest20241209/lib/python3.10/site-packages/empress/_plot_utils.py", line 13, in <module>
    from bp import parse_newick
  File "/home/marcus/anaconda3/envs/etest20241209/lib/python3.10/site-packages/bp/__init__.py", line 8, in <module>
    from ._bp import BP
  File "bp/_bp.pyx", line 1, in init bp._bp
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

```

## Solving the issue

If we again create a fresh conda environment, but this time use a version of numpy before 2, then this solves the problem:

```console
$ mamba create -n etest20241209-2 python=3.10 "numpy < 2" cython  # installs numpy 1.26.4
$ conda activate etest20241209-2
$ pip install empress
$ empress --help  # now works as usual!
```

## Proposed solution

It is not clear from your error log if you are using some sort of environment manager (e.g. conda). If not, I recommend doing so (and using a version of numpy < 2 when creating an environment), then installing Empress into such an environment. [mamba](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html), in particular, works fairly well from what I've seen (this is what I used in the above tests). I think installing Empress in this way should fix the problem.

**Alternative solution:** I think you could fix the issues in your current system by manually downgrading the installed numpy version to an earlier version than 2 (that is, assuming that you already have such a numpy version installed -- you can check by running `pip list | grep numpy`). **However, I am not sure this is ideal:** I suspect this error is happening in the first place because some other piece of software was recently installed that required a more recent numpy version, which caused numpy to be upgraded (which in turn caused this problem). I worry that downgrading numpy in your current system would make Empress work, but then break the hypothetical other package you have installed that relies on a more recent version of numpy :)

## Fixing this in Empress

Maybe we should pin `numpy < 2` for now? The traceback indicates that the error occurs in [iow](https://github.com/biocore/improved-octo-waddle), but I am not 100% sure about if the root of the issue comes from iow or from something else.

**Comment by bpeacock44** [comment]
Thank you so much! Specifying numpy in a conda environment has fixed the issue for me as well. (I had used an environment before but hadn't thought to specify numpy.)

**Comment by fedarko** [comment]
Perfect, glad that worked!
